name: VSMP
version: '${project.version}'
main: blake_jh.vsmp.VSMP
api-version: 1.19
authors: [ Blake_JH ]
description: A plugin developed by Blake_JH for Vitalize SMP.
commands:
  store:
    description: sends the url to the server store to the the command sender.
    usage: /store
    aliases: store
    permission: vitalize.store
  announce:
    description: allows the sender of the command to announce strings of text.
    usage: /announce
    aliases: announce
    permission: vitalize.announce
  clearchat:
    description: allows the sender of the command to clear the chat.
    usage: /clearchat
    aliases: clearchat
    permission: vitalize.clearchat


